#ifndef SOUNDMANAGER_GLOBAL_H
#define SOUNDMANAGER_GLOBAL_H

#include <qglobal.h>

#ifdef SOUNDMANAGER_LIB
# define SOUNDMANAGER_EXPORT Q_DECL_EXPORT
#else
# define SOUNDMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // SOUNDMANAGER_GLOBAL_H
